# Generated by Django 6.0.7 on 2026-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("wallet", "Wallet"), ("gateway", "Gateway")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
